apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

transformers:
# use the builtin namespace transformer to set the namespace
- |- 
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    # name: status-app
    namespace: dev
  unsetOnly: false

patches:
- path: deployment-dev.yaml
# args needs special treatment
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "dev app running ğŸ™‚ğŸ‘"
  target:
    kind: Deployment
- path: service-dev.yaml

