apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: deployment-prod.yaml
# args needs special treatment
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "prod app running ğŸ™‚ğŸ‘"
  target:
    kind: Deployment
- path: service-prod.yaml


